version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tautin_db
      POSTGRES_USER: admintautin
      POSTGRES_PASSWORD: admintautin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
